services:
  database:
    image: postgres:alpine
    user: postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - './db-data:/var/lib/cadexdb/data'
    healthcheck:
      test: 'pg_isready -U user --dbname=postgres'
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
      - '5432:5432'
  adminer:
    image: 'adminer:latest'
    environment:
      ADMINER_DEFAULT_SERVER: 'database'
    restart: 'unless-stopped'
    ports:
      - '8180:8080'
    depends_on:
      - database

#  back:
#    image: maven:3.9-ibmjava-8
#    restart: unless-stopped
#    environment:
#      - SPRING_DATASOURCE_URL=jdbc:postgresql://database:5432/$DB_NAME
#      - SPRING_DATASOURCE_USERNAME=$DB_USERNAME
#      - SPRING_DATASOURCE_PASSWORD=$YDB_PASSWORD
#      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
#      - SPRING_MAIL_USERNAME=$YOUR_MAIL_USERNAME
#      - SPRING_MAIL_PASSWORD=$YOUR_MAIL_PASSWORD
#    depends_on:
#      - database
#    ports:
#      - "9090:8080"
#    volumes:
#      - ".:/usr/src/server"
#    working_dir: "/usr/src/server"
#    command: ["mvn", "spring-boot:run"]
